services:
  db:
    image: postgres:16-alpine
    container_name: journalix-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-journalix}
    ports:
      - "5433:5432"
    volumes:
      - journalix_pgdata:/var/lib/postgresql/data

volumes:
  journalix_pgdata:
